version: '3'

services:
  mysql:
    container_name: mysql
    hostname: mysql-host
    image: mysql:8.4
    ports:
      - 3310:3306
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: senha
      MYSQL_DATABASE: sistema_reservas_de_salas
      MYSQL_USER: usuario
      MYSQL_PASSWORD: senha
      TZ: America/Sao_Paulo
